---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure metricbeat is started and enabled at boot
  service:
    name: metricbeat
    state: started
    enabled: yes
  when: metricbeat_enabled

- name: Ensure metricbeat is not started and not enabled at boot
  service:
    name: metricbeat
    state: stopped
    enabled: no
  when: not metricbeat_enabled

- name: Copy metricbeat configuration
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: 0644
  notify: restart metricbeat

- stat:
    path: /etc/metricbeat/modules
  register: modules

- name: Clear metricbeat modules configuration
  file: 
    path: /etc/metricbeat/modules.d/
    state: absent
  when: modules.stat.exists

- name: Create metric modules folder
  file:
    path: /etc/metricbeat/modules.d/
    state: directory
    group: root
    owner: root
    mode: 0655
  
- name: Copy metricbeat file modules configuration  
  copy:
    src: modules/{{ item }}.yml
    dest: /etc/metricbeat/modules.d/{{ item }}.yml
    owner: root
    group: root
    mode: 0644
  with_items: "{{ metricbeat_file_modules | default(['system']) }}"
  notify: restart metricbeat

- name: Build metricbeat template modules configuration  
  template:
    src: modules/{{ item }}.yml.j2
    dest: /etc/metricbeat/modules.d/{{ item }}.yml
    owner: root
    group: root
    mode: 0644
  with_items: "{{ metricbeat_modules | default([]) }}"
  notify: restart metricbeat

- name: Export metricbeat template
  command: >
    metricbeat export template
  register: metricbeat_template
  when: metricbeat_setup_templates

- name: Install metricbeat template on elasticsearch
  uri:
    url: "{{ metricbeat_elasticsearch_endpoint }}/_template/metricbeat-6.1.3"
    method: PUT
    body: "{{ metricbeat_template.stdout }}"
    body_format: json
  when: metricbeat_setup_templates

- name: Setup kibana dashboards
  command: > 
    metricbeat setup --dashboards 
  when: metricbeat_setup_templates